console.log("Hello world!") //For Print Something...

console.log("Hey, Harsh !!") //For Print Something...

console.log(1234567890) //For Print Something...

console.log(true) //For Print Something...

console.log(null) //For Print Something...

console.log(undefined) //For Print Something...

console.log([1, 2, 3, 4, 5]) //For Print Something...

console.log({ name: "John", age: 30 }) //For Print Something...

console.log(function() {
  console.log("This is a function");
}); //For Print Something...

console.log(new Date()) //For Print Something...

console.log(Symbol("This is a symbol")) //For Print Something...

console.log(BigInt(9007199254740991)) //For Print Something...

console.log(new Map([[1, "One"], [2, "Two"]])) //For Print Something...

console.log(new Set([1, 2, 3, 4, 5])) //For Print Something...

console.log(new RegExp("Hello", "g")) //For Print Something...

console.log(new Promise((resolve, reject) => {
  resolve("Promise resolved");
}
)); //For Print Something...
